/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'danny' at '2/23/15 8:46 PM' with Gradle 1.10
 *
 * @author danny, @date 2/23/15 8:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
